# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-26 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_auto_20170424_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bug',
            name='status',
            field=models.CharField(choices=[('O', 'Open'), ('I', 'In Progress'), ('D', 'Delivered'), ('F', 'Fixed'), ('C', 'Closed')], default='Open', max_length=10),
        ),
        migrations.AlterField(
            model_name='bug',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
