# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-26 18:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_auto_20170426_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bug',
            name='closed',
        ),
    ]
