# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-26 20:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_remove_bug_closed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bug',
            old_name='created_date',
            new_name='updated_date',
        ),
    ]
