# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-09 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_auto_20170426_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
