# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-17 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_bug_issue_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='issue_type',
            field=models.CharField(choices=[('BUG', 'Bug'), ('FTR', 'Feature')], default='Bug', max_length=10),
        ),
    ]
